### PR TITLE
add application service interface

### PR DESCRIPTION
**Pull request by faiq**

### CODE REVIEW

**Comment by termie** [comment]
does this compile

**Comment by termie** [comment]
does this compile now

**Comment by faiq** [comment]
yup.

**Comment by termie** [comment]
+1

**Comment by flenter** [comment]
Why only support GetApplication here? If we create per 'domain' interfaces why not include all functions for that domain?

**Comment by faiq** [comment]
Thats true, i mean i guess we can add it... doesn't really matter, but all of our projects that use it need to implement the other functions as well

**Pull request merged**
